### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by zhkuang** [Famous/engine#311]
Not sure why I am getting this. 

```` javascript
Node Modules not yet installed, attempting to do so now.

> fsevents@0.3.6 install /Users/raijin/Documents/famous/hello/node_modules/watchify/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

-

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.



/

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.


gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 69
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/raijin/Documents/famous/hello/node_modules/watchify/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing fsevents@0.3.6
npm WARN addRemoteGit git+https://github.com/ariya/esprima.git#harmony resetting remote /Users/raijin/.npm/_git-remotes/https-github-com-ariya-esprima-git-9ee8156d because of error: You have not agreed to the Xcode license agreements, please run 'xcodebuild -license' (for user-level acceptance) or 'sudo xcodebuild -license' (for system-wide acceptance) from within a Terminal window to review and agree to the Xcode license agreements.
npm ERR! git clone --template=/Users/raijin/.npm/_git-remotes/_templates --mirror https://github.com/ariya/esprima.git /Users/raijin/.npm/_git-remotes/https-github-com-ariya-esprima-git-9ee8156d: You have not agreed to the Xcode license agreements, please run 'xcodebuild -license' (for user-level acceptance) or 'sudo xcodebuild -license' (for system-wide acceptance) from within a Terminal window to review and agree to the Xcode license agreements.
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code 69

npm ERR! Command failed: git clone --template=/Users/raijin/.npm/_git-remotes/_templates --mirror https://github.com/ariya/esprima.git /Users/raijin/.npm/_git-remotes/https-github-com-ariya-esprima-git-9ee8156d
npm ERR!
npm ERR! You have not agreed to the Xcode license agreements, please run 'xcodebuild -license' (for user-level acceptance) or 'sudo xcodebuild -license' (for system-wide acceptance) from within a Terminal window to review and agree to the Xcode license agreements.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/raijin/Documents/famous/hello/npm-debug.log

> engine-seed@1.0.0 dev /Users/raijin/Documents/famous/hello
> node ./bin/dev.js

serving /Users/raijin/Documents/famous/hello/public on port 1618
Error: Cannot find module 'famous/dom-renderables/DOMElement' from '/Users/raijin/Documents/famous/hello/src'
Error: Cannot find module 'famous/core/FamousEngine' from '/Users/raijin/Documents/famous/hello/src'
````

**Comment by alexanderGugel** [comment]
The seed project has a dependency on watchify. [watchiy](https://www.npmjs.com/package/watchify) is being used in order to auto recompile the browserify bundle whenever you change a file.

In order to achieve this, watchify needs to be notified whenever a file change using [chokidar](https://www.npmjs.com/package/chokidar). chokidar has a dependency on [fsevents](https://www.npmjs.com/package/fsevents).

And here is the problem. fsevents is primarily [written in C++](https://github.com/strongloop/fsevents) and therefore needs to be compiled. That's why you need to agree to the Xcode/iOS license to get access to the Xcode command line utilities. In order to agree to the license, you need to have admin privileges.

In order to fix this, just run `gcc` and follow the instructions there.

**Comment by zhkuang** [comment]
Thanks for the super quick response. It's work. Thanks a lot!!

**Comment by zhkuang** [comment]
Thanks for the super quick response. It's work . Thanks a lot!!

**Comment by michaelobriena** [comment]
@alexanderGugel Thanks for the response.
