### ISSUE TITLE
Running `famouse create` fails with ETIMEDOUT

### ISSUE THREAD

**Issue by evil-shrike** [Famous/engine#442]
I've installed famous-cli and trying to create a project. It fails. I'm behind http proxy. But npm works fine. I tried to set http_proxy environment variable.
```
C:\>npm install -g famous-cli
C:\>famous -v
0.5.2

C:\>famous create test
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: connect ETIMEDOUT
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
```

**Comment by michaelobriena** [comment]
@evil-shrike can you refile this at https://github.com/famous/famous-cli?  Thanks.

**Comment by evil-shrike** [comment]
ok. Famous/famous-cli#71
